config/routes.rb
Rails.application.routes.draw do
  resources :ords do
    resources :ord_items
  end

  resources :gmapps

  # get 'book_offline/index'
  # resources :orders do
  #   resources :ordered_items
  # end

  resources :restaurants do
    resources :reviews
    resources :book_offline
    resources :menus
  end

  resources :users do
    resources :reviews
    resources :ords
  end
  resources :reviews

  # get 'home_page/new'
  resources :users, only: %i[create show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home_page#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/admin', to: 'admin_panel#index'
  get '/admin/approval', to: 'admin_panel#approval_panel', as: 'admin_approval'
  post '/reviews/:id/edit', to: 'reviews#update'
  get '/user/:id/reviews/check', to: 'reviews#check'
  post '/restaurants/:id/book_offline/new', to: 'book_offline#create'
  get '/user/:id/bookings', to: 'users#appointments', as: 'appointments'
  get '/orders/gmpass', to: 'orders#gmapss'
  get '/search', to: 'restaurants#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/gmapp.rb
class Gmapp < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/ord.rb
class Ord < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :ord_items, dependent: :destroy
end

app/models/ord_item.rb
class OrdItem < ApplicationRecord
  belongs_to :ord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy
  has_many :ords, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  def address; end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?

  has_secure_password

  has_many :reviews, dependent: :destroy
  has_many :ords, dependent: :destroy
  has_many :books, dependent: :destroy
  validates :email, presence: true, uniqueness: true, format: { with: /\A\S+@.+\.\S+\z/ }
  validates :password, presence: true

  def set_defaults
    self.isadmin = false if isadmin.nil?
  end
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  def index
    if logged_in? && current_user.isadmin
      @users = User.all
      @restaurants = Restaurant.all
    else
      redirect_to login_path
    end
  end

  def approval_panel
    @reviews = Review.where(isApproved: false) if logged_in? && current_user.isadmin
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gmapps_helper.rb
module GmappsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ord_items_helper.rb
module OrdItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ords_helper.rb
module OrdsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_panel/approval_panel.html.erb
<div class="user-greeting">
<h1>Reviews for Approval </h1>
</div>

<div class="rest-cont">
<% @reviews.each do |review|%>
<div class="card rest-con">
<% @user= User.find(review.user_id)%>
<% @restaurant= Restaurant.find(review.restaurant_id)%>
<div class="card-body">
<h5 class="card-title">Username-: <%= @user.username%></h5>
<h5 class="card-title">Restaurants-: <%= @restaurant.name%></h5>
<h5 class="card-title">Ratings-: <%= review.ratings%></h5>
<%= link_to "Accept Review", edit_review_url(review),class:"btn btn-primary",method: :post %>
<%= link_to "Delete", review_path(review),class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
</div>                  
</div>
<% end %>
</div>

app/views/admin_panel/index.html.erb
<div class="admin-cover">
<div class="card admin-card">
    <div class="card-header">
        <h1 class="card-title">Admin Panel</h1>
    </div>
    <div class="card-body">
        <h4 class="card-title">Number of users registered <%= @users.count %> </h4>
        <h4 class="card-title">Number of hotels registered <%= @restaurants.count %> </h4> 
        <%= link_to "Show Hotels",  restaurants_path, class:"btn btn-secondary"%>
        <%= link_to "Register Hotels",   new_restaurant_path, class:"btn btn-danger"%>
    </div>
</div>
</div>

