config/routes.rb
Rails.application.routes.draw do
  resources :ords do
    resources :ord_items
  end

  resources :gmapps

  # get 'book_offline/index'
  # resources :orders do
  #   resources :ordered_items
  # end

  resources :restaurants do
    resources :reviews
    resources :book_offline
    resources :menus
  end

  resources :users do
    resources :reviews
    resources :ords
  end
  resources :reviews

  # get 'home_page/new'
  resources :users, only: %i[create show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home_page#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/admin', to: 'admin_panel#index'
  get '/admin/approval', to: 'admin_panel#approval_panel', as: 'admin_approval'
  post '/reviews/:id/edit', to: 'reviews#update'
  get '/user/:id/reviews/check', to: 'reviews#check'
  post '/restaurants/:id/book_offline/new', to: 'book_offline#create'
  get '/user/:id/bookings', to: 'users#appointments', as: 'appointments'
  get '/orders/gmpass', to: 'orders#gmapss'
  get '/search', to: 'restaurants#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/gmapp.rb
class Gmapp < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/ord.rb
class Ord < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :ord_items, dependent: :destroy
end

app/models/ord_item.rb
class OrdItem < ApplicationRecord
  belongs_to :ord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy
  has_many :ords, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  def address; end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?

  has_secure_password

  has_many :reviews, dependent: :destroy
  has_many :ords, dependent: :destroy
  has_many :books, dependent: :destroy
  validates :email, presence: true, uniqueness: true, format: { with: /\A\S+@.+\.\S+\z/ }
  validates :password, presence: true

  def set_defaults
    self.isadmin = false if isadmin.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: %i[show edit]

  def new
    if !logged_in?
      @user = User.new
    else
      redirect_to login_path
    end
  end

  def create
    if logged_in?
      flash[:notice] = 'Cant create new user while logged in'
      redirect_to login_path
    end

    @user = User.new(user_params)
    @user.email = @user.email.downcase
    if @user.valid?
      @user.save
      redirect_to @user
    else
      redirect_to signup_path
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to login_path if current_user.id != @user.id
    @city = request.location.city
    @restaurants = Restaurant.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if !logged_in?
      redirect_to login_path

    else
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def appointments
    @book = Book.where(user_id: current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :isadmin, :latitude,
                                 :longitude)
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gmapps_helper.rb
module GmappsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ord_items_helper.rb
module OrdItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ords_helper.rb
module OrdsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/appointments.html.erb
<div class="user-greeting">
<h2>Restaurants Appointments </h2>
</div>


<div class="rest-cont">
<% @book.reverse_each do |b|%>
 <% @restaurant= Restaurant.find(b.restaurant_id)%>
 <div class="card rest-con">
  <h3 class="card-header"><%= @restaurant.name %></h3>
  <div class="card-body">
   <h5 class="card-title">Heads -: <%= b.head %></h5>
   <h5 class="card-title">Booking Date -:<%= b.booked_on%></h5>
   <h5 class="card-title">Booking Time -:<%= b.booked_at%></h5>
 </div>
 </div>
<hr/>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="signUp">
<br/>
<h1 class="sign-up">Update User Details</h1>
<%= form_with model: @user,class:"container form-g"  do |form| %>

  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :username %><br>
    <%= form.text_field :username, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %><br>
    <%= form.password_field :password, class:"form-control" %><br>
  </div>

   <div class="form-group">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password , class:"form-control"%><br>
  </div>

   <div class="form-group">
    <%= form.label :latitude %><br>
    <%= form.number_field :latitude, step: :any, class:"form-control" %><br>
  </div>

   <div class="form-group">
    <%= form.label :longitude %><br>
    <%= form.number_field :longitude, step: :any, class:"form-control" %><br>
  </div>


    <%= form.submit "Update User",class:"btn btn-danger"%>
<% end %>

</div>

app/views/users/new.html.erb
<div class="signUp">
 <h1 class="sign-up">Sign Up </h1>
 <%= form_with model: @user, class:"container form-g" do |f|%>
  <div class="form-group">
    <%= f.label :email%><br/>
    <%= f.text_field :email, placeholder: "Email", class:"form-control"%>
  </div>
  <div class="form-group"> 
    <%= f.label :username%><br/>
    <%= f.text_field :username, placeholder: "Username", class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :password%><br/>
    <%= f.password_field :password, placeholder: "Password", class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation%><br/>
    <%= f.password_field :password_confirmation, placeholder: "Confirm password", class:"form-control"%>
  </div>    
    <br/>
   <%= f.submit "Create Account", class:"btn btn-danger"%>
 <% end %>
<div>

app/views/users/show.html.erb
<% if flash.any? %>
<% flash.each do |notice, msg|%>
<div class="alert alert-info">
<%= msg%>
</div>
<% end %>
<% end %>




<div class="usr-contain">
 <div class="user-greeting">
  <h1>Welcome <%= @user.username %> !</h1>
 </div>

  <div class="hotel-heading">
  <h4> User Panel</h4>
 </div>


 <div class="user-panel">
 <h5 class="user-list"><%= link_to "Show Appointments", appointments_path, class:"btn btn-secondary" %></h5>
 <% if !current_user.isadmin?%>
  <h5 class="user-list"><%= link_to "See reviews", user_reviews_url(@user),class:"btn btn-secondary" %></h5>
 <% end %>
 <h5 class="user-list"><%= link_to "Show current order", gmapps_path,class:"btn btn-secondary" %></h5>

 <% if @user.isadmin%>          
    <h5 class="user-list"><%= link_to "Admin Panel", admin_path,class:"btn btn-secondary" %></h5>
    <h5 class="user-list"><%= link_to "Admin Review Panel", admin_approval_path,class:"btn btn-secondary" %></h5>
  <% end %>

 <% if current_user == @user%>
    <h5 class="user-list"><%=  link_to "Update User Profile", edit_user_path,class:"btn btn-secondary"%> </h5>
    <h5 class="user-list"> <%= button_to "Logout", logout_path, class:"btn btn-danger"%></h5>
   <% end %>   
</div>

 <div class="hotel-heading">
  <h4> All hotels registered on Potato </h4>
 </div>

   <div class="rest-cont">
<% @restaurants.each do|r|%>
<div class="card rest-con">
    <h3 class="card-header"><%= r.name%></h3>
    <div class="card-body">
     <h5 class="card-title"><%= r.category%></h5>
    <%= link_to "More Details", r, class:"btn btn-secondary"%>
    </div>
</div>
<% end %>
</div>
</div>


app/views/users/user_reviews.html.erb
<% @reviews.each do |rev|%>
<div class="card rest-con">
    <% @restaurant=Restaurant.find(rev.restaurant_id) %>
    <h4><%= @restaurant.name%></h4>
    <h6><%= rev.ratings%></h6>
    <%= link_to "Update Review", edit_review_url(rev)%>
    <br/>
</div>
<% end %>