config/routes.rb
Rails.application.routes.draw do
  resources :ords do
    resources :ord_items
  end

  resources :gmapps

  # get 'book_offline/index'
  # resources :orders do
  #   resources :ordered_items
  # end

  resources :restaurants do
    resources :reviews
    resources :book_offline
    resources :menus
  end

  resources :users do
    resources :reviews
    resources :ords
  end
  resources :reviews

  # get 'home_page/new'
  resources :users, only: %i[create show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home_page#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/admin', to: 'admin_panel#index'
  get '/admin/approval', to: 'admin_panel#approval_panel', as: 'admin_approval'
  post '/reviews/:id/edit', to: 'reviews#update'
  get '/user/:id/reviews/check', to: 'reviews#check'
  post '/restaurants/:id/book_offline/new', to: 'book_offline#create'
  get '/user/:id/bookings', to: 'users#appointments', as: 'appointments'
  get '/orders/gmpass', to: 'orders#gmapss'
  get '/search', to: 'restaurants#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/gmapp.rb
class Gmapp < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/ord.rb
class Ord < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :ord_items, dependent: :destroy
end

app/models/ord_item.rb
class OrdItem < ApplicationRecord
  belongs_to :ord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy
  has_many :ords, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  def address; end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?

  has_secure_password

  has_many :reviews, dependent: :destroy
  has_many :ords, dependent: :destroy
  has_many :books, dependent: :destroy
  validates :email, presence: true, uniqueness: true, format: { with: /\A\S+@.+\.\S+\z/ }
  validates :password, presence: true

  def set_defaults
    self.isadmin = false if isadmin.nil?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    if logged_in?
      @restaurant = Restaurant.all
    else
      redirect_to login_path
    end
  end

  def show
    if logged_in?
      @restaurant = Restaurant.find(params[:id])
    else
      redirect_to login_path
    end
  end

  def new
    if logged_in? && current_user.isadmin?
      @restaurant = Restaurant.new
    else
      flash[:new] = 'Only admin can register new restaurants'
      redirect_to login_path
    end
  end

  def create
    @restaurant = Restaurant.create(params_create)
    if @restaurant.save
      redirect_to @restaurant

    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if logged_in? && current_user.isadmin?
      @restaurant = Restaurant.find(params[:id])
    else
      flash[:new] = 'Only admin can register new restaurants'
      redirect_to login_path
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if params[:restaurant][:pictures].present?
      params[:restaurant][:pictures].each do |image|
        @restaurant.pictures.attach(image)
      end
    end
    if @restaurant.update(resturant_params)
      redirect_to @restaurant
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path, status: :see_other
  end

  def search
    unless logged_in?
      flash[:notice] = 'Please Signup/Login'
      redirect_to login_path
    end

    @restaurants1 = Restaurant.where('name LIKE ?', '%' + params[:search] + '%')
    @restaurants2 = Restaurant.near(params[:search], 50).order('distance')
  end

  private

  def params_create
    params.require(:restaurant).permit(:name, :category, :resturant_type, :latitude, :longitude, pictures: [])
  end

  def resturant_params
    params.require(:restaurant).permit(:name, :category, :resturant_type)
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gmapps_helper.rb
module GmappsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ord_items_helper.rb
module OrdItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ords_helper.rb
module OrdsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/restaurants/edit.html.erb

<div class="signUp">
<h1 class="sign-up">Update Information</h1>
<%= form_with model: @restaurant, class:"container form-g" do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :category %><br>
    <%= form.text_field :category,class:"form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label :resturant_type %><br>
    <%= form.text_field :resturant_type ,class:"form-control"%><br>
  </div>

  <div class="form-group">
    <%= form.label :latitude %><br>
    <%= form.number_field :latitude,class:"form-control"%>
 </div>

 <div class="form-group">
    <%= form.label :longitude %><br>
    <%= form.number_field :longitude,class:"form-control"%>
 </div>

   <div class="form-group">
    <%= form.label :pictures %><br>
    <%= form.file_field :pictures, multiple: true%>
  </div>

<br/>
  <div class="form-group">
    <%= form.submit class:"btn btn-danger" %>
  </div>
<% end %>
</div>

app/views/restaurants/index.html.erb
<div class="user-greeting">
  <h1> Restaurants</h1>
 </div>

<div class="rest-cont">
<% @restaurant.each do |r|%>
<div class="card rest-con">
<h3 class="card-header"><%= r.name%></h3>
<div class="card-body">
     <h5 class="card-title"><%= r.category%></h5>
    <%= link_to "More Details", r, class:"btn btn-secondary"%>
</div>
</div>
<br/>
<% end %>
</div>

app/views/restaurants/new.html.erb
<div class="signUp">
<h1 class="sign-up">Register Hotels</h1>
<%= form_with model: @restaurant, class:"container form-g" do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :category %><br>
    <%= form.text_field :category ,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :resturant_type %><br>
    <%= form.text_field :resturant_type ,class:"form-control"%>
  </div>

 <div class="form-group">
    <%= form.label :latitude %><br>
    <%= form.number_field :latitude,class:"form-control"%>
 </div>

 <div class="form-group">
    <%= form.label :longitude %><br>
    <%= form.number_field :longitude,class:"form-control"%>
 </div>

  <div class="form-group">
    <%= form.label :pictures %><br>
    <%= form.file_field :pictures, multiple: true ,class:"form-control"%>
  </div>

 
<br/>
  <div class="form-group">
    <%= form.submit "Create Restaurant", class:"btn btn-danger"%>
  </div>
<% end %>
</div>

app/views/restaurants/search.html.erb
<div class="user-greeting">
  <h1> Restaurants</h1>
 </div>

<div class="rest-cont">
<% @restaurants1.each do |r|%>
<div class="card rest-con">
<h3 class="card-header"><%= r.name%></h3>
<div class="card-body">
     <h5 class="card-title"><%= r.category%></h5>
    <%= link_to "More Details", r, class:"btn btn-secondary"%>
</div>
</div>
<br/>
<% end %>
<% @restaurants2.each do |r|%>
<div class="card rest-con">
<h3 class="card-header"><%= r.name%></h3>
<div class="card-body">
     <h5 class="card-title"><%= r.category%></h5>
    <%= link_to "More Details", r, class:"btn btn-secondary"%>
</div>
</div>
<br/>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="card rest-con">
 <h2 class="rest-name"><%= @restaurant.name%><h2>
 <div class="card-body">
   <h3 class="card-title"> Category -:<%= @restaurant.category%></h3>
   <h3 class="card-title">Type -: <%= @restaurant.resturant_type%></h3>
   <%= link_to "See Menu", restaurant_menus_path(@restaurant.id), class:"btn btn-danger" %>
   <%= link_to "Book Table", new_restaurant_book_offline_path(@restaurant.id), class:"btn btn-secondary"%>
 </div>
</div>

<% if current_user.isadmin?%>
<div class="restaurant-admin-p">
<h4 class="card-title">Admin Controls</h4>
<div>
<%= link_to "Update Information", edit_restaurant_path, class:"btn btn-secondary" %>
<%= link_to "Delete Restaurant", restaurant_path(@restaurant),class:"btn btn-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
 </div>                        
 </div>        
<% end %>

<h3 class="card-title restaurant-admin-p"> Images </h3>

<div class="container rest-pics">
<% @restaurant.pictures.each do |picture|%>
  <%= image_tag picture.variant(resize_to_limit: [300,300]).processed%>
<% end %>
</div>

<h3 class="rest-name">Upload Pictures</h3>
<%= form_with model: @restaurant do |form| %>
  <div class="restaurant-admin-p">
    <%= form.file_field :pictures, multiple: true, class:"btn btn-secondary form-pic", required:"required"%>
    <%= form.submit "Upload Pictures", class:"btn btn-primary" %>
  </div> 
<% end %>

<h3 class="rest-name"> Add review about the hotel-: </h3>
<%= form_with model: [ @restaurant, @restaurant.reviews.build ] do |form| %>
  <div class="form-group ratings">
  <div>
    <strong><%= form.label :ratings, "Add Review" %></strong>
    <%= form.text_field :ratings, class:"form-control-md", required:"required" %>
  </div>
  <br/>
    <%= form.submit "Submit", class:"btn btn-primary"  %>
  
<% end %>
  </div>


<h3 class="rest-name"> Reviews on Resturant </h3>
<% @restaurant.reviews.each do |review| %>
 <% if review.isApproved%>
 <div class="card rest-con">
   <h4 class="card-title">
    <strong>Username:</strong>
    <% @user= User.find(review.user_id)%>
    <%= @user.username %>
   </h4>

   <h4 class="card-title">
    <strong>Comment:</strong>
    <%= review.ratings %>
   </h4>
   </div>
  <% end %>
<% end %>
<br/>
