config/routes.rb
Rails.application.routes.draw do
  resources :ords do
    resources :ord_items
  end

  resources :gmapps

  # get 'book_offline/index'
  # resources :orders do
  #   resources :ordered_items
  # end

  resources :restaurants do
    resources :reviews
    resources :book_offline
    resources :menus
  end

  resources :users do
    resources :reviews
    resources :ords
  end
  resources :reviews

  # get 'home_page/new'
  resources :users, only: %i[create show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home_page#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/admin', to: 'admin_panel#index'
  get '/admin/approval', to: 'admin_panel#approval_panel', as: 'admin_approval'
  post '/reviews/:id/edit', to: 'reviews#update'
  get '/user/:id/reviews/check', to: 'reviews#check'
  post '/restaurants/:id/book_offline/new', to: 'book_offline#create'
  get '/user/:id/bookings', to: 'users#appointments', as: 'appointments'
  get '/orders/gmpass', to: 'orders#gmapss'
  get '/search', to: 'restaurants#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/gmapp.rb
class Gmapp < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/ord.rb
class Ord < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :ord_items, dependent: :destroy
end

app/models/ord_item.rb
class OrdItem < ApplicationRecord
  belongs_to :ord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :menus, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy
  has_many :ords, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  def address; end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?

  has_secure_password

  has_many :reviews, dependent: :destroy
  has_many :ords, dependent: :destroy
  has_many :books, dependent: :destroy
  validates :email, presence: true, uniqueness: true, format: { with: /\A\S+@.+\.\S+\z/ }
  validates :password, presence: true

  def set_defaults
    self.isadmin = false if isadmin.nil?
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/gmapps_helper.rb
module GmappsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ord_items_helper.rb
module OrdItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ords_helper.rb
module OrdsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Potato",root_path, class:"navbar-brand b-title"%> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if !logged_in?%>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class:"nav-link whh" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", login_path, class:"nav-link whh" %>
        </li>
      <% else %>
         <li class="nav-item">
          <%= link_to "User Profile",'/users/'+ current_user.id.to_s, class:"nav-link whh" %>
        </li>
        <li class="nav-item">
          <%= link_to "Hotels", restaurants_path, class:"nav-link whh" %>
        </li>
        <% end %>
      </ul>

    <%= form_tag '/search',method: :get , remote: true, class:"d-flex" do |f| %>
      <%= text_field_tag  :search,"", class:"form-control me-2", required:"required", placeholder:"Search Restaurants,Locations"%>
      <%= submit_tag "Search", class:"btn btn-outline-danger" %>
    <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potato</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
  
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <div class= "contain">
    <%= yield %>
    </div>
  </body>
</html>